# This workflow will test a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: ['8', '11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'adopt'
    - name: Run tests on Windows after setting HOME environment variable
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        $env:HOME = $env:HOMEPATH
        echo "Set HOME to $HOME"
        gradle test
#      uses: gradle/gradle-build-action@v1
#      with:
#        gradle-version: current
#        arguments: test
#      env:
#        HOME: $HOMEPATH
    - name: Run tests on POSIX
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        gradle test
#      uses: gradle/gradle-build-action@v1
#      with:
#        gradle-version: current
#        arguments: test
