# This workflow will test a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  schedule:  # at 03:06 on day-of-month 8
    - cron: '6 3 8 * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: ['8', '11', '17', '21']

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'adopt'
    - name: Setup Gradle for Java < 21
      if: ${{ matrix.java-version != '21' }}
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '7.6.4'
    - name: Setup Gradle for Java 21
      if: ${{ matrix.java-version == '21' }}
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.13'
    - name: Set Gradle proprties
      run: |
        echo "org.jetbrains.dokka.experimental.gradle.pluginMode=V2EnabledWithHelpers" > gradle.properties
    - name: Run tests on Windows after setting HOME environment variable
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        $env:HOME = $env:HOMEPATH
        echo "Set HOME to $HOME"
        gradle test
    - name: Run tests on POSIX
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        gradle test
